language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
  - pip install -r test_requirements.txt
  - pip install django==$DJANGO_VERSION
  - pip install -e .

script:
  - coverage run --source=save_the_change setup.py test

after_success:
  - coveralls
